#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/config/application.php';
require_once __DIR__ . '/app/constants.php';
require_once __DIR__ . '/app/ruleset.php';
require_once __DIR__ . '/app/helpers.php';
require_once __DIR__ . '/app/setup.php';